// This file is autogenerated. Changes will be overwritten.
#include "M52TBSWIPT/moc_add_todo.cpp"
#include "M52TBSWIPT/moc_edit_todo.cpp"
#include "M52TBSWIPT/moc_history.cpp"
#include "M52TBSWIPT/moc_mainwindow.cpp"
