# This Python file uses the following encoding: utf-8
from PySide6.QtWidgets import QWidget, QAbstractItemView, QMessageBox
from PySide6.QtCore import QAbstractItemModel, QDateTime,QTime, Signal,Qt
from ui.ui_add_todo import Ui_Add_Todo  # Import the UI class generated by pyside6-uic
from src.control_unit import ControlUnit
from src.helper import refreshTodos
from src.todo import Todo

class AddTodo(QWidget):
    """
    AddTodo is the class that interacts with the window that shows up when the user clicks on the Add Todo button.
    """
    refreshData=Signal(name="RefreshData")

    def __init__(self, parent=None,database=None):
        """
        Constructor for the AddTodo window.
        """
        super().__init__(parent)
        self.database=database

        self.ui = Ui_Add_Todo()
        self.ui.setupUi(self)

        self.tableView = None  # To store the passed table model
        self.setAttribute(Qt.WA_DeleteOnClose)




        # Connect button actions to slots
        self.ui.pushButton_3.clicked.connect(self.on_pushButton_3_clicked)  # Cancel button
        self.ui.pushButton_4.clicked.connect(self.on_pushButton_4_clicked)  # Add Todo button
    def setup_values(self,date,isDateTime=False):
        if (isDateTime):
            self.date=date
        else:
            self.date=QDateTime(date,QTime(0, 0))
        self.date=self.date.addSecs(90)
        self.ui.dateTimeEdit_3.setDateTime(self.date)
        self.date=self.date.addSecs(60*60*2+30)
        self.ui.dateTimeEdit_4.setDateTime(self.date)
        self.date=date

    def passTable(self, p: QAbstractItemModel):
        """
        Method to pass the table of Todos from the main window into this window.
        """
        self.tableView = p

    def on_pushButton_3_clicked(self):
        """
        Actions taken when the Cancel button is pressed.
        """
        self.close()  # Close the current window when cancel is pressed

    def on_pushButton_4_clicked(self):
            """
            Actions taken when the Add Todo button is pressed.
            """
            #Add Todo Button
            name=self.ui.plainTextEdit_2.toPlainText()
            startDate=self.ui.dateTimeEdit_3.text()
            endDate=self.ui.dateTimeEdit_4.text()
            tag=self.ui.comboBoxTags.currentText()
            date = QDateTime.currentDateTime()
            is_completed=self.ui.checkBox.isChecked()


            start=QDateTime.fromString(startDate,"dd/MM/yyyy hh:mm")
            end=QDateTime.fromString(endDate,"dd/MM/yyyy hh:mm")
            if (len(name)<=150):
                #if (date.secsTo(start)>=0 and date.secsTo(end)>0):
                    if (start.secsTo(end)>0):
                        cu  =  ControlUnit(self.database)
                        formattedTime = date.toString("dd/MM/yyyy hh:mm")
                        todo=Todo(name,startDate,endDate,formattedTime,0,tag)
                        cu.AddTodo(todo)
                        if (is_completed):
                            cu.UpdateTodoStatus(todo,"Completed")
                        self.refreshData.emit()
                        self.close()
                    else:
                        QMessageBox.critical(self, "Incorrect Date", "Start Date is after End Date!")

                #else:
                #    QMessageBox.critical(self, "Incorrect Date", "Start Date or End Date are set before current date!")

            else:
                QMessageBox.critical(self, "Name is too long", "The name of the Todo exceeds 150 characters!")

    def __del__(self):
        """
        Destructor for the window.
        """
        del self.ui
if __name__ == "__main__":
        import sys
        from PySide6.QtWidgets import QApplication
        from database import Database


        # Create the application instance
        app = QApplication(sys.argv)
        database = Database()
        database.openDB()
        database.createTables()

        # Create an instance of MyWidget
        widget = AddTodo(database=database)

        # Show the widget
        widget.show()

        # Start the application's event loop
        sys.exit(app.exec())
