# This Python file uses the following encoding: utf-8
from PySide6.QtWidgets import QWidget,QMessageBox
from PySide6.QtCore import Slot, QDateTime,Signal, Qt
from PySide6.QtGui import QStandardItemModel
from ui.ui_edit_todo import Ui_Edit_Todo  # Import the UI class generated by pyside6-uic
from src.control_unit import ControlUnit
from src.todo import Todo
from src.helper import refreshTodos


# Assuming Todo is a Python class defined elsewhere
# from todo import Todo

class Edit_Todo(QWidget):
    refreshData=Signal(name="RefreshData")

    def __init__(self, parent=None,database=None):
        super().__init__(parent)
        self.database=database
        self.id=None

        self.ui = Ui_Edit_Todo()
        self.ui.setupUi(self)

        self.tableView = None  # To store the passed table model
        self.setAttribute(Qt.WA_DeleteOnClose)

        # Connect button actions to slots
        #self.ui.pushButton_3.clicked.connect(self.on_pushButton_3_clicked)  # Cancel button
        #self.ui.pushButton_4.clicked.connect(self.on_pushButton_4_clicked)  # Edit Todo button

    def setValues(self, td):
        start_date = QDateTime.fromString(td.getStartDate(),"dd/MM/yyyy hh:mm")
        self.ui.dateTimeEdit_3.setDateTime(start_date)
        end_date = QDateTime.fromString(td.getEndDate(),"dd/MM/yyyy hh:mm")
        self.id = td.getId()
        self.ui.dateTimeEdit_4.setDateTime(end_date)
        self.ui.plainTextEdit_2.document().setPlainText(td.getName())
        self.ui.comboBoxTags.setCurrentIndex(self.ui.comboBoxTags.findText(td.getTag()))

    def passTable(self, p):
        self.tableView = p

    @Slot()
    def on_pushButton_3_clicked(self):
        self.close()  # Close the current window when cancel is pressed

    @Slot()
    def on_pushButton_4_clicked(self):
        #Edit Todo Button
        name=self.ui.plainTextEdit_2.toPlainText()
        startDate=self.ui.dateTimeEdit_3.text()
        endDate=self.ui.dateTimeEdit_4.text()
        tag=self.ui.comboBoxTags.currentText()

        date = QDateTime.currentDateTime()
        start=QDateTime.fromString(startDate,"dd/MM/yyyy hh:mm")
        end=QDateTime.fromString(endDate,"dd/MM/yyyy hh:mm")
        if (len(name)<=150):
            #if (date.secsTo(start)>=0 and date.secsTo(end)>0):
                if (start.secsTo(end)>0):
                    cu  =  ControlUnit(self.database)
                    td = Todo(name,startDate,endDate,"",self.id,tag)
                    cu.EditTodo(td)
                    self.refreshData.emit()
                    self.close()

                else:
                    QMessageBox.critical(self, "Incorrect Date", "Start Date is after End Date!")


            #else:
            #    QMessageBox.critical(self, "Incorrect Date", "Start Date or End Date are set before current date!")


        else:
            QMessageBox.critical(self, "Name is too long", "The name of the Todo exceeds 150 characters!")
    def __del__(self):
        del self.ui

if __name__ == "__main__":
    import sys
    from PySide6.QtWidgets import QApplication
    from database import Database


    # Create the application instance
    app = QApplication(sys.argv)
    database = Database()
    database.openDB()

    # Create an instance of MyWidget
    widget = Edit_Todo(database=database)
    td = Todo("abc","23/10/2025 11:09","23/10/2025 12:09","23/10/2025 09:08", 0, "Productivity")
    widget.setValues(td)


    # Show the widget
    widget.show()

    # Start the application's event loop
    sys.exit(app.exec())

