# This Python file uses the following encoding: utf-8
from PySide6.QtCore import Qt, QDateTime, QAbstractItemModel,Signal, QTime
from PySide6.QtSql import QSqlQuery,QSqlQueryModel
from PySide6.QtWidgets import QAbstractItemView, QHeaderView, QMessageBox, QWidget
import os


from ui.ui_listview import Ui_ListView  # Import the UI class generated by pyside6-uic
from src.add_todo import AddTodo
from src.edit_todo import Edit_Todo
from src.todo import Todo
from src.control_unit import ControlUnit


class CustomListView(QWidget):
    #refreshData=Signal(name="RefreshData")

    def __init__(self,database,parent=None,refresh_function=None):
        super().__init__(parent)
        self.parent=parent
        self.database=database
        self.ui=Ui_ListView()
        self.ui.setupUi(self.parent)
        self.setAttribute(Qt.WA_DeleteOnClose)
        self.refresh_function=refresh_function
        self.edit_todo=None
        self.add_todo=None


        self.ui.tableView.setWordWrap(True)
        self.ui.tableView.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.ui.tableView.setModel(QSqlQueryModel(self.parent))

        query=QSqlQuery(self.database.DB)
        query.prepare("SELECT ID, NAME, STATUS, START_DATE, END_DATE, DATE_CREATED, TAG FROM Todo WHERE STATUS <> \"Completed\";")
        self.ui.tableView.model().setQuery(query)

        self.ui.tableView.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)

        self.refreshTodos()

        #self.ui.tableView.setColumnWidth(0,20)
        #self.ui.tableView.setColumnWidth(1,300)
        #elf.ui.tableView.setColumnWidth(2,100)
        #self.ui.tableView.setColumnWidth(3,125)
        #self.ui.tableView.setColumnWidth(4,125)
        #self.ui.tableView.setColumnWidth(5,125)
        #self.ui.tableView.setColumnWidth(6,125)



        self.ui.add_button.clicked.connect(self.on_add_button_clicked)
        self.ui.edit_button.clicked.connect(self.on_edit_button_clicked)
        self.ui.delete_button.clicked.connect(self.on_delete_button_clicked)
        self.ui.mark_as_completed_button.clicked.connect(self.on_mark_as_complete_button)
        self.ui.start_daily_button.clicked.connect(self.on_daily_todo_button)

    def refreshTodos(self):
        self.ui.tableView.model().refresh()

    def on_add_button_clicked(self):
        del self.add_todo
        self.add_todo = AddTodo(database=self.database)
        self.add_todo.refreshData.connect(self.refresh_function)
        self.add_todo.setup_values(QDateTime.currentDateTime(),isDateTime=True)
        self.add_todo.setWindowTitle("Add Todo")
        self.add_todo.setWindowModality(Qt.ApplicationModal)

        self.add_todo.show()


    def on_edit_button_clicked(self):
        select=self.ui.tableView.selectionModel()
        id=select.selectedRows(0)[0].data()
        name=select.selectedRows(1)[0].data()
        stat=select.selectedRows(2)[0].data()
        sd=select.selectedRows(3)[0].data()
        ed=select.selectedRows(4)[0].data()
        dc=select.selectedRows(5)[0].data()
        tag=select.selectedRows(6)[0].data()

        if (not (id==0 and name=="" and stat=="" and ed=="" and sd=="" and dc=="")):
            del self.edit_todo
            self.edit_todo = Edit_Todo(database=self.database)
            self.edit_todo.refreshData.connect(self.refresh_function)

            self.edit_todo.setWindowTitle("Edit Todo")
            #edit_todo.passTable(ui->tableView->model())
            self.edit_todo.setWindowModality(Qt.ApplicationModal)

            td=Todo(name,sd,ed,dc,id,tag)


            self.edit_todo.setValues(td)

            self.edit_todo.show()

        else:
            QMessageBox.critical(self, "No Todo Selected", "Please select Todo to edit!")

    def on_delete_button_clicked(self):
        select=self.ui.tableView.selectionModel()
        id=select.selectedRows(0)[0].data()
        name=select.selectedRows(1)[0].data()
        stat=select.selectedRows(2)[0].data()
        sd=select.selectedRows(3)[0].data()
        ed=select.selectedRows(4)[0].data()
        dc=select.selectedRows(5)[0].data()
        tag=select.selectedRows(6)[0].data()

        if (not (id==0 and name=="" and stat=="" and ed=="" and sd=="" and dc=="")):
            td=Todo(name,sd,ed,dc,id,tag)
            reply = QMessageBox.question(self.parent, "Delete Todo", "Are you sure you want to delete the selected Todo?",QMessageBox.Yes|QMessageBox.No)
            if (reply == QMessageBox.Yes):
                cu=ControlUnit(database=self.database)
                td.updateStatus("Deleted")
                cu.DeleteTodo(td)
                self.refresh_function()
        else:
            QMessageBox.critical(self, "No Todo Selected", "Please select Todo to delete!")

    def on_mark_as_complete_button(self):
        select=self.ui.tableView.selectionModel()
        id=select.selectedRows(0)[0].data()
        name=select.selectedRows(1)[0].data()
        stat=select.selectedRows(2)[0].data()
        sd=select.selectedRows(3)[0].data()
        ed=select.selectedRows(4)[0].data()
        dc=select.selectedRows(5)[0].data()
        tag=select.selectedRows(6)[0].data()

        if (not (id==0 and name=="" and stat=="" and ed=="" and sd=="" and dc=="")):
            td=Todo(name,sd,ed,dc,id,tag)
            cu=ControlUnit(database=self.database)

            cu.UpdateTodoStatus(td,"Completed")
            self.refresh_function()
        else:
            QMessageBox.critical(self, "No Todo Selected", "Please select Todo to Complete!")
    def on_daily_todo_button(self):
        # Daily Todos:
        reply = QMessageBox.question(
            self.parent,
            "Renew Old Daily Todos",
            "Are you sure you want to delete and restart the Daily Todos?",
            QMessageBox.Yes | QMessageBox.No
        )

        if reply == QMessageBox.Yes:
            date = QDateTime.currentDateTime()
            suffix = " (Daily)*"

            # In Progress timestamps
            start = date.toString("dd/MM/yyyy hh:mm")

            date.setTime(QTime(23, 59, 0))
            end = date.toString("dd/MM/yyyy hh:mm")

            date.setTime(QTime(0, 0, 0))
            created = date.toString("dd/MM/yyyy hh:mm")

            # Remove existing daily todos
            self.database.removeDaily(suffix)

            delimiter = "||"

            # Create daily_todos.txt if it doesn't exist
            if not os.path.exists("daily_todos.txt"):
                with open("daily_todos.txt", "w", encoding="utf-8") as file:
                    file.write(f"Daily todo that you have specified in daily_todos.txt 1{delimiter}\n")
                    file.write(f"Daily todo that you have specified in daily_todos.txt 2{delimiter}\n")

            cu = ControlUnit(database=self.database)

            # Read and add todos
            with open("daily_todos.txt", "r", encoding="utf-8") as file:
                for line in file:
                    parts = line.strip().split(delimiter)

                    name = parts[0].strip() + suffix
                    tag = "Daily"

                    if len(parts) > 1 and parts[1].strip():
                        tag = parts[1].strip()
                    td=Todo(name, start, end, created,0, tag)

                    cu.AddTodo(td)

            # Refresh UI
            self.refresh_function()
    def __del__(self):
        del self.ui
