# This Python file uses the following encoding: utf-8
from PySide6.QtCore import QDateTime, QDate, Qt
from PySide6.QtWidgets import QWidget, QTableView, QSizePolicy, QVBoxLayout, QHeaderView
from PySide6.QtGui import QStandardItemModel
from ui.ui_timetable import Ui_TimeTable  # Import the UI class generated by pyside6-uic
#from cpp_custom_classes import MyTableModel

class TimeTable(QWidget):
    def __init__(self,database,parent=None):
        super().__init__(parent)
        self.ui = Ui_TimeTable()
        self.ui.setupUi(self)
        self.database=database
        self.setAttribute(Qt.WA_DeleteOnClose)
        self.model = QStandardItemModel(self)
        self.ui.Table.setModel(self.model)
        self.ui.Table.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)  # Make Table expand
        self.ui.Table.horizontalHeader().setStretchLastSection(True)
        self.ui.Table.verticalHeader().setStretchLastSection(True)
        self.ui.Table.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.ui.Table.verticalHeader().setSectionResizeMode(QHeaderView.Stretch)

        # Optional: hide scrollbars if you never want overflow
        self.ui.Table.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.ui.Table.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)


        layout = QVBoxLayout(self)
        layout.addWidget(self.ui.Table)
        self.setLayout(layout)

        self.create_columns()

    def create_columns(self):
        columns = []
        rows = []
        self.model.clear()
        self.model.setRowCount(12)
        self.model.setColumnCount(7)


        # Start date is 3 days before the current date
        startDate = QDate.currentDate().addDays(-3)

        for i in range(7):
            date = startDate.addDays(i).toString("dd/MM")
            columns.append(date)

            date = startDate.addDays(i).toString("dd/MM/yyyy")
            allTodoOfTheDay = self.database.getTodoOfTheDay(date)
            for j in range(0, 24, 2):
                self.populateColumn(j, i, date, allTodoOfTheDay)

        # Set the horizontal header labels (days of the week)
        model = self.ui.Table.model()
        #if isinstance(model, QStandardItemModel):
        model.setHorizontalHeaderLabels(columns)




        # Set the vertical header labels (hours of the day)
        for i in range(0, 24, 2):
            rows.append(self.getHour(i))

        #if isinstance(model, QStandardItemModel):
        model.setVerticalHeaderLabels(rows)

        # Resize rows and columns to fit contents
        self.ui.Table.resizeRowsToContents()
        self.ui.Table.resizeColumnsToContents()

    def getHour(self, row: int) -> str:
        hours = ""

        if row < 10:
            hours = f" 0{row}"
        else:
            hours = f" {row}"

        hours += ":00 -\n"
        row += 2

        if row < 10:
            hours += f" 0{row}"
        else:
            hours += f" {row}"

        hours += ":00"

        return hours

    def populateColumn(self, row: int, column: int, date: str, all_todo_of_the_day):
        hours, limit = "", ""

        if row < 10:
            hours = f" 0{row}"
            if row < 9:
                limit = f" 0{row+1}"
            else:
                limit = f" {row+1}"
        else:
            hours = f" {row}"
            limit = f" {row+1}"

        cell_content = self.getCellData(all_todo_of_the_day, date + limit)

        self.ui.Table.model().setData(self.ui.Table.model().index(row//2, column), cell_content)


    def getCellData(self, s, period):
        cellData = ""

        i = 0
        while i < len(s):
            todo = s[i]
            start_date = QDateTime.fromString(todo.getStartDate(), "dd/MM/yyyy hh:mm")
            upper_bound = QDateTime.fromString(period + ":59", "dd/MM/yyyy hh:mm")

            if not (start_date <= upper_bound):
                return cellData

            # Add data to cellData
            cellData += f"{todo.getName()} ({todo.getId()})\n"

            # Now check the end date
            end_date = QDateTime.fromString(todo.getEndDate(), "dd/MM/yyyy hh:mm")
            if end_date <= upper_bound:
                s.pop(i)  # Remove the item from list
            else:
                i += 1

        return cellData.strip()  # Trimmed result
    def __del__(self):
        del self.ui
